# -*- coding: utf-8 -*-
"""combined_gconvgru_cnn_sop (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sumHB2OWLK1yHhMvNq5U9x0KwtQn6yX
"""

import torch

!pip uninstall torch-scatter torch-sparse torch-geometric torch-cluster  --y
!pip install torch-scatter -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install torch-cluster -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install git+https://github.com/pyg-team/pytorch_geometric.git

!pip install torch_geometric_temporal

!pip install torch_geometric==2.4.0

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
trgt=pd.read_csv('/content/drive/MyDrive/Data/la_main.csv')
nbr1=pd.read_csv('/content/drive/MyDrive/Data/la_nbr1.csv')
nbr2=pd.read_csv('/content/drive/MyDrive/Data/la_nbr2.csv')
nbr3=pd.read_csv('/content/drive/MyDrive/Data/sd_nbr.csv')
nbr4=pd.read_csv('/content/drive/MyDrive/Data/sd_train.csv')

trgt_test=pd.read_csv('/content/drive/MyDrive/Data/la_main_test.csv')
nbr1_test=pd.read_csv('/content/drive/MyDrive/Data/la_nbr1test.csv')
nbr2_test=pd.read_csv('/content/drive/MyDrive/Data/la_nbr2test.csv')
nbr3_test=pd.read_csv('/content/drive/MyDrive/Data/sd_nbr_test.csv')
nbr4_test=pd.read_csv('/content/drive/MyDrive/Data/sd_ca_test.csv')

train_list=['trgt','nbr1','nbr2','nbr3','nbr4']

for df in train_list:
  print(globals()[df].columns)

columns_to_drop=['Minute', 'Clearsky GHI',
        'Dew Point', 'Solar Zenith Angle','Precipitable Water', 'Fill Flag']



for df in train_list:
  globals()[df].drop(columns=columns_to_drop,inplace=True,errors='ignore')

for df in train_list:
  print(globals()[df].columns)

for df in train_list:
  print(globals()[df].count())

for df in train_list:
    # Drop rows where a particular column has value zero
    globals()[df] = globals()[df][globals()[df]['GHI'] != 0]

for df in train_list:
 globals()[df].drop(globals()[df].tail(1).index,inplace=True)

# def remove_outliers(df):
#     Q1 = df['GHI'].quantile(0.25)
#     Q3 = df['GHI'].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
#     df_filtered = df[(df['GHI'] >= lower_bound) & (df['GHI'] <= upper_bound)]
#     return df_filtered

# # Assuming you have 5 DataFrames df1, df2, df3, df4, and df5
# # Check and remove outliers from each DataFrame for the 'GHI' column
# for df in train_list:
#     df_dummy=globals()[df]
#     df_cleaned = remove_outliers(df_dummy)
#     # Update the original DataFrame with the cleaned data
#     globals()[df[:]] = df_cleaned[:]



for df in train_list:
    globals()[df]['Datetime'] = pd.to_datetime(globals()[df][['Year', 'Month', 'Day', 'Hour']])
    globals()[df].set_index('Datetime', inplace=True)



common_index = set.intersection(*[set(globals()[df].index) for df in train_list])
common_index=list(common_index)
for df in train_list:
    globals()[df] = globals()[df].loc[common_index]

for df in train_list:
  globals()[df].sort_index(inplace=True)

drop=['Year','Month','Day','Hour']
for df in train_list:
  for d in drop:
    globals()[df].drop(d,axis=1,inplace=True)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
for df in train_list:
  scaled_values=scaler.fit_transform(globals()[df])
  scaled=pd.DataFrame(scaled_values, columns=globals()[df].columns)
  globals()[df]=scaled

for df in train_list:
  print(globals()[df].columns)

for df in train_list:
  print(globals()[df].count())





# def remove_outliers(df):
#     Q1 = df['GHI'].quantile(0.25)
#     Q3 = df['GHI'].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
#     df_filtered = df[(df['GHI'] >= lower_bound) & (df['GHI'] <= upper_bound)]
#     return df_filtered

# # Assuming you have 5 DataFrames df1, df2, df3, df4, and df5
# # Check and remove outliers from each DataFrame for the 'GHI' column
# for df in train_list:
#     df_dummy=globals()[df]
#     df_cleaned = remove_outliers(df_dummy)
#     # Update the original DataFrame with the cleaned data
#     globals()[df[:]] = df_cleaned[:]











trgt.head()

trgt_ghi=trgt['GHI']
nbr1_ghi=nbr1['GHI']
nbr2_ghi=nbr2['GHI']
nbr3_ghi=nbr3['GHI']
nbr4_ghi=nbr4['GHI']

import numpy as np

def create_sequences(data, sequence_length):
    sequences = []
    targets = []

    for i in range(len(data) - sequence_length):
        seq = data[i:i+sequence_length]
        target = data.iloc[i+sequence_length]
        sequences.append(seq)
        targets.append(target)

    return np.array(sequences), np.array(targets)

window_size=10

node1_features,node1_targets=create_sequences(trgt_ghi,window_size)
node2_features,node2_targets=create_sequences(nbr1_ghi,window_size)
node3_features,node3_targets=create_sequences(nbr2_ghi,window_size)
node4_features,node4_targets=create_sequences(nbr3_ghi,window_size)
node5_features,node5_targets=create_sequences(nbr4_ghi,window_size)

node_features=[]
node_features.append([node1_features,node2_features,node3_features,node4_features,node5_features])

node_features=np.array(node_features)

node_features.shape

node_features=node_features.reshape(17534,5,10,)

num_nodes=5

sources = []
targets = []

# Generate edges for the complete graph
for i in range(num_nodes):
    for j in range(i + 1, num_nodes):  # Avoid self-loops by starting from i+1
        sources.append(i)
        targets.append(j)

# Combine source and target indices into edge_index tensor
edge_index = torch.tensor([sources, targets], dtype=torch.long)

print("Edge Index for the 5 by 5 complete graph:")
print(edge_index)

node_targets=[]
node_targets.append([node1_targets,node2_targets,node3_targets,node4_targets,node5_targets])

node_targets=np.array(node_targets)

node_targets=node_targets.reshape(17534,5,1)

for df in train_list:
  globals()[df]=globals()[df].drop('GHI',axis=1)

for df in train_list:
  globals()[df]=globals()[df].reindex(trgt.columns,axis=1)

for df in train_list:
  print(globals()[df].head())

index=0
correlation=[]
for index in range (len(trgt)-10):
  df_matrix=[]
  for df in train_list:
    df_matrix.append(globals()[df].iloc[index+10])
  new_df=pd.DataFrame(df_matrix)
  new_df=pd.DataFrame(df_matrix)
  corr_col=new_df.corr()
  corr_col_matrix=corr_col.values
  corr_row=new_df.transpose().corr()
  corr_row_matrix=corr_row.values
  corr=np.concatenate((corr_col_matrix,corr_row_matrix),axis=0)
  corr = np.nan_to_num(corr,1)
  correlation.append(corr)
  index=index+1

correlation=np.array(correlation)
correlation=correlation.reshape(17534,10,5,1)

correlation=correlation.reshape(17534,1,10,5)
correlation=torch.tensor(correlation,dtype=torch.float32)

from torch_geometric_temporal.signal import StaticGraphTemporalSignal

signal=StaticGraphTemporalSignal(edge_weight=None,edge_index=edge_index,features=node_features,targets=node_targets)

signal[0]

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import GConvGRU

class GCN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GConvGRU(input_dim, hidden_dim, K=2)
        self.conv2=GConvGRU(hidden_dim,hidden_dim,K=2)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x=self.conv2(x,edge_index)
        x=F.tanh(x)
        x = self.fc(x)
        return x

class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        # First convolutional layer with 128 kernels of size 3x3
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=128, kernel_size=3, stride=1, padding=1)
        # Second convolutional layer with 64 kernels of size 3x3
        self.conv2 = nn.Conv2d(in_channels=128, out_channels=64, kernel_size=3, stride=1, padding=1)
        # Activation function
        self.relu = nn.ReLU()
        # Max pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        # Fully connected layer
        self.fc = nn.Linear(128, 10)  # Input size depends on the spatial dimensions of the output from the previous layer

    def forward(self, x):
        # Forward pass through the first convolutional layer
       #
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool(x)
        # Forward pass through the second convolutional layer
        x = self.conv2(x)
        x = self.relu(x)
        x = self.pool(x)
        # Flatten the output from the convolutional layers
        x = x.view(-1, 128)
        # Forward pass through the fully connected layer
        x = self.fc(x)
        return x

gcn_input_dim=10
gcn_hidden_dim=128
gcn_output_dim=10

class CombinedModel(nn.Module):
    def __init__(self, gcn_input_dim, gcn_hidden_dim, gcn_output_dim):
        super(CombinedModel, self).__init__()
        self.gcn_model = GCN(gcn_input_dim, gcn_hidden_dim, gcn_output_dim)
        self.cnn_model = ConvNet()
        self.fc=nn.Linear(60,10)
        self.fc2=nn.Linear(10,1)

    def forward(self, x_gcn, edge_index, x_cnn):
        output_gcn = self.gcn_model(x_gcn, edge_index)
        output_cnn = self.cnn_model(x_cnn)
        output_cnn=torch.flatten(output_cnn)
        output_gcn=torch.flatten(output_gcn)
        z=torch.cat((output_gcn,output_cnn),axis=0)
        z=self.fc(z)
        z=F.relu(z)
        z=self.fc2(z)
        return z

model=CombinedModel(gcn_input_dim,gcn_hidden_dim,gcn_output_dim)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

from tqdm import tqdm



num_epochs = 10
for epoch in tqdm(range(num_epochs)):
    model.train()
    total_loss = 0

    for time,(data,matrix) in enumerate(zip((signal),correlation)):
        optimizer.zero_grad()
        node_feature, edge_index = data.x, data.edge_index
        #print(data.y)
        #print(data.x.shape)

        predicted_value = model(node_feature, edge_index, matrix)
        #print(predicted_value[0])
        #print("predicted value is:",predicted_value.shape)
        label = data.y
        #print('label shape is:',label.shape)
        loss = criterion(predicted_value, label[0])
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    # Calculate the average loss for the epoch
    avg_loss = total_loss /(time+1)

    # Print the average loss for the epoch
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}")

test_list=['trgt_test','nbr1_test','nbr2_test','nbr3_test','nbr4_test']

columns_to_drop=['Minute', 'Clearsky GHI',
        'Dew Point', 'Solar Zenith Angle','Precipitable Water', 'Fill Flag']



for df in test_list:
  globals()[df].drop(columns=columns_to_drop,inplace=True,errors='ignore')

for df in test_list:
  print(globals()[df].columns)



for df in test_list:
  print(globals()[df].count())

for df in test_list:
    # Drop rows where a particular column has value zero
    globals()[df] = globals()[df][globals()[df]['GHI'] != 0]

for df in test_list:
 globals()[df].drop(globals()[df].tail(1).index,inplace=True)

# def remove_outliers(df):
#     Q1 = df['GHI'].quantile(0.25)
#     Q3 = df['GHI'].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
#     df_filtered = df[(df['GHI'] >= lower_bound) & (df['GHI'] <= upper_bound)]
#     return df_filtered

# # Assuming you have 5 DataFrames df1, df2, df3, df4, and df5
# # Check and remove outliers from each DataFrame for the 'GHI' column
# for df in train_list:
#     df_dummy=globals()[df]
#     df_cleaned = remove_outliers(df_dummy)
#     # Update the original DataFrame with the cleaned data
#     globals()[df[:]] = df_cleaned[:]

for df in test_list:
    globals()[df]['Datetime'] = pd.to_datetime(globals()[df][['Year', 'Month', 'Day', 'Hour']])
    globals()[df].set_index('Datetime', inplace=True)



common_index = set.intersection(*[set(globals()[df].index) for df in test_list])
common_index=list(common_index)
for df in test_list:
    globals()[df] = globals()[df].loc[common_index]

for df in test_list:
  globals()[df].sort_index(inplace=True)

drop=['Year','Month','Day','Hour']
for df in test_list:
  for d in drop:
    globals()[df].drop(d,axis=1,inplace=True)

# trgt_test_ghi=trgt_test['GHI']
# nbr1_test_ghi=nbr1_test['GHI']
# nbr2_test_ghi=nbr2_test['GHI']
# nbr3_test_ghi=nbr3_test['GHI']
# nbr4_test_ghi=nbr4_test['GHI']


# trgt_test_ghi=np.array(trgt_test_ghi)
# nbr1_test_ghi=np.array(nbr1_test_ghi)
# nbr2_test_ghi=np.array(nbr2_test_ghi)
# nbr3_test_ghi=np.array(nbr3_test_ghi)
# nbr4_test_ghi=np.array(nbr4_test_ghi)
# #nbr5_test_ghi=np.array(nbr5_test_ghi)

from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler()
scaler2 = MinMaxScaler()
scaler3=MinMaxScaler()
scaler4=MinMaxScaler()
scaler5=MinMaxScaler()
trgt_test_ghi=scaler1.fit_transform(trgt_test[['GHI']]).flatten()
nbr1_test_ghi=scaler2.fit_transform(nbr1_test[['GHI']]).flatten()
nbr2_test_ghi=scaler3.fit_transform(nbr2_test[['GHI']]).flatten()
nbr3_test_ghi=scaler4.fit_transform(nbr3_test[['GHI']]).flatten()
nbr4_test_ghi=scaler5.fit_transform(nbr4_test[['GHI']]).flatten()

import numpy as np

def create_sequences_array(data, sequence_length):
    sequences = []
    targets = []

    for i in range(len(data) - sequence_length):
        seq = data[i:i+sequence_length]
        target = data[i+sequence_length]
        sequences.append(seq)
        targets.append(target)

    return np.array(sequences), np.array(targets)

node1_features_test,node1_targets_test=create_sequences_array(trgt_test_ghi,window_size)
node2_features_test,node2_targets_test=create_sequences_array(nbr1_test_ghi,window_size)
node3_features_test,node3_targets_test=create_sequences_array(nbr2_test_ghi,window_size)
node4_features_test,node4_targets_test=create_sequences_array(nbr3_test_ghi,window_size)
node5_features_test,node5_targets_test=create_sequences_array(nbr4_test_ghi,window_size)

node_features_test=[]
node_features_test.append([node1_features_test,node2_features_test,node3_features_test,node4_features_test,node5_features_test])

node_features_test=np.array(node_features_test)

node_features_test.shape

node_features_test=node_features_test.reshape(4466,5,10,)

node_targets_test=[]
node_targets_test.append([node1_targets_test,node2_targets_test,node3_targets_test,node4_targets_test,node5_targets_test])

node_targets_test=np.array(node_targets_test)

node_targets_test.shape

node_targets_test=node_targets_test.reshape(4466,5,1)

for df in test_list:
  globals()[df]=globals()[df].drop('GHI',axis=1)

for df in test_list:
  globals()[df]=globals()[df].reindex(trgt_test.columns,axis=1)

scaler_test=MinMaxScaler()

for df in test_list:
  df_scale=scaler_test.fit_transform(globals()[df])
  scaled_df=pd.DataFrame(df_scale,columns=globals()[df].columns)
  globals()[df]=scaled_df

index=0
correlation_test=[]
for index in range (len(trgt_test)-10):
  df_matrix=[]
  for df in test_list:
    df_matrix.append(globals()[df].iloc[index+10])
  new_df=pd.DataFrame(df_matrix)
  new_df=pd.DataFrame(df_matrix)
  corr_col=new_df.corr()
  corr_col_matrix=corr_col.values
  corr_row=new_df.transpose().corr()
  corr_row_matrix=corr_row.values
  corr=np.concatenate((corr_col_matrix,corr_row_matrix),axis=0)
  corr = np.nan_to_num(corr,1)
  correlation_test.append(corr)
  index=index+1

correlation_test=np.array(correlation_test)
#correlation_test=correlation.reshape(17533,10,5,1)

correlation_test=correlation_test.reshape(4466,1,10,5)
correlation_test=torch.tensor(correlation_test,dtype=torch.float32)

signal_test=StaticGraphTemporalSignal(edge_weight=None,edge_index=edge_index,features=node_features_test,targets=node_targets_test)

model.eval()

y_true=[]
y_pred=[]
with torch.no_grad():
  for time,(data,matrix) in enumerate(zip(signal_test,correlation_test)):
        node_feature_test, edge_index_test = data.x, data.edge_index
        #print(data.y)
        #print(data.x.shape)

        predicted_value = model(node_feature_test, edge_index_test, matrix)
        #print(predicted_value[0])
        #print("predicted value is:",predicted_value.shape)
        label = data.y
        y_true.extend(label[0].numpy())
        y_pred.extend(predicted_value.numpy())
        #print('label shape is:',label.shape)
        loss = criterion(predicted_value, label[0])
        #loss.backward()
        #optimizer.step()

        total_loss += loss.item()

    # Calculate the average loss for the epoch
  avg_loss = total_loss /(time+1)

print(np.sqrt(avg_loss))

y_true=np.array(y_true)

y_true=scaler1.inverse_transform(y_true.reshape(-1,1)).flatten()

y_pred=np.array(y_pred)
y_pred=scaler1.inverse_transform(y_pred.reshape(-1,1)).flatten()

from sklearn.metrics import r2_score
r2 = r2_score(y_true, y_pred)
print("R2 Score:", r2)

from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y_true, y_pred))

from sklearn.metrics import mean_squared_error
print(np.sqrt(mean_squared_error(y_true, y_pred)))

from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_true, y_pred))

df_result=pd.DataFrame(y_pred)
df_result.to_excel('/content/drive/MyDrive/results_gconv-cnn.xlsx')

